//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlDiffLib.Tests {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlDiffLib.Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;catalog&gt;
        ///  &lt;book id=&quot;bk101&quot;&gt;
        ///    &lt;author&gt;Gambardella, Matthew&lt;/author&gt;
        ///    &lt;title&gt;XML Developer&apos;s Guide&lt;/title&gt;
        ///    &lt;genre&gt;Computer&lt;/genre&gt;
        ///    &lt;price&gt;44.95&lt;/price&gt;
        ///    &lt;publish_date&gt;2000-10-01&lt;/publish_date&gt;
        ///    &lt;description&gt;
        ///      An in-depth look at creating applications
        ///      with XML.
        ///    &lt;/description&gt;
        ///  &lt;/book&gt;
        ///  &lt;book id=&quot;bk102&quot;&gt;
        ///    &lt;author&gt;Ralls, Kim&lt;/author&gt;
        ///    &lt;title&gt;Midnight Rain&lt;/title&gt;
        ///    &lt;genre&gt;Fantasy&lt;/genre&gt;
        ///    &lt;price&gt;5.95&lt;/price&gt;
        ///    &lt;publish_date&gt;2000-12-16&lt;/publish_ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string exampleA {
            get {
                return ResourceManager.GetString("exampleA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;catalog&gt;
        ///  &lt;book id=&quot;bk101&quot;&gt;
        ///    &lt;author&gt;Gambardella, Matthew&lt;/author&gt;
        ///    &lt;title&gt;XML Developer&apos;s Guide&lt;/title&gt;
        ///    &lt;genre&gt;Computer&lt;/genre&gt;
        ///    &lt;price&gt;44.95&lt;/price&gt;
        ///    &lt;publish_date&gt;2015-10-12&lt;/publish_date&gt;
        ///    &lt;description&gt;
        ///      An in-depth look at creating applications
        ///      with XML.
        ///    &lt;/description&gt;
        ///  &lt;/book&gt;
        ///  &lt;book id=&quot;bk102&quot;&gt;
        ///    &lt;author&gt;Ralls, Kim&lt;/author&gt;
        ///    &lt;title&gt;Midnight Rain&lt;/title&gt;
        ///    &lt;genre&gt;Mystery&lt;/genre&gt;
        ///    &lt;price&gt;5.95&lt;/price&gt;
        ///    &lt;publish_date&gt;2016-02-16&lt;/publish_ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string exampleB {
            get {
                return ResourceManager.GetString("exampleB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;ModulePosting
        ///	CPKFile=&quot;&quot;
        ///	Mode=&quot;Test&quot;
        ///	TypeOfPost=&quot;Post&quot;&gt;
        ///	&lt;Company
        ///		Address1=&quot;6500 Pinecrest Dr Ste 100&quot;
        ///		Address2=&quot;&quot;
        ///		AltPhone=&quot;&quot;
        ///		AltPhoneExt=&quot;&quot;
        ///		CMPProductID=&quot;3506&quot;
        ///		City=&quot;Plano&quot;
        ///		CompanyCode=&quot;&quot;
        ///		CompanyData=&quot;&quot;
        ///		CompanyID=&quot;10032162&quot;
        ///		ContractNumber=&quot;&quot;
        ///		CountyMutual=&quot;&quot;
        ///		EMail=&quot;&quot;
        ///		Fax=&quot;&quot;
        ///		GenericFinanceAPRCharge=&quot;0&quot;
        ///		GenericFinanceAPRCharge2=&quot;0&quot;
        ///		GenericFinanceAPR_FlatChargeAmount=&quot;31&quot;
        ///		GenericFinanceAPR_FlatChargeAmount2=&quot;31&quot;
        ///		GenericFinanceAmountNotFinanced=&quot;100 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string HAAR01000 {
            get {
                return ResourceManager.GetString("HAAR01000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;ModulePosting
        ///	CPKFile=&quot;&quot;
        ///	Mode=&quot;Test&quot;
        ///	TypeOfPost=&quot;Post&quot;&gt;
        ///	&lt;Company
        ///		Address1=&quot;6500 Pinecrest Dr Ste 100&quot;
        ///		Address2=&quot;&quot;
        ///		AltPhone=&quot;&quot;
        ///		AltPhoneExt=&quot;&quot;
        ///		CMPProductID=&quot;3506&quot;
        ///		City=&quot;Plano&quot;
        ///		CompanyCode=&quot;&quot;
        ///		CompanyData=&quot;&quot;
        ///		CompanyID=&quot;10032162&quot;
        ///		ContractNumber=&quot;&quot;
        ///		CountyMutual=&quot;&quot;
        ///		EMail=&quot;&quot;
        ///		Fax=&quot;&quot;
        ///		GenericFinanceAPRCharge=&quot;0&quot;
        ///		GenericFinanceAPRCharge2=&quot;0&quot;
        ///		GenericFinanceAPR_FlatChargeAmount=&quot;31&quot;
        ///		GenericFinanceAPR_FlatChargeAmount2=&quot;31&quot;
        ///		GenericFinanceAmountNotFinanced=&quot;100 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string HAAR01001 {
            get {
                return ResourceManager.GetString("HAAR01001", resourceCulture);
            }
        }
    }
}
